services:
  backend:
    image: fuguone/borgdash-backend:latest
    container_name: borgdash-backend
    env_file: .env
    ports:
      - "8157:8000"
    volumes:

      - /docker/config/borgdash:/app/data
      - ./ssh_keys/id_rsa:/app/host_keys/ssh_key:ro  # ssh keys
      - ./data/source:/app/source:ro                 # data to backup (can add multiple lines)
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: fuguone/borgdash-frontend:latest
    container_name: borgdash-frontend
    env_file: .env
    ports:
      - "3157:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local
  ssh_keys:
    driver: local

networks:
  default:
    name: borgdash-network
